exclude:
- /.eslintrc.js
- /Gruntfile.js
- /docs/.*
- /eslint-rules/.*
- /examples/.*
- /fixtures/.*
- /flow/.*
- /grunt/.*
- /gulp/tasks/.*
- /gulpfile.js
- /mocks/.*
- /packages/.*
- /scripts/.*
- /src/__mocks__/vendor/third_party/WebComponents.js
- /src/addons/__tests__/.*
- /src/addons/transitions/__tests__/.*
- /src/isomorphic/__tests__/React-test.js
- /src/isomorphic/children/__tests__/.*
- /src/isomorphic/classic/__tests__/ReactContextValidator-test.js
- /src/isomorphic/classic/class/__tests__/.*
- /src/isomorphic/classic/element/__tests__/.*
- /src/isomorphic/classic/types/__tests__/.*
- /src/isomorphic/modern/element/__tests__/.*
- /src/node_modules/.*
- /src/renderers/__tests__/.*
- /src/renderers/art/__tests__/ReactART-test.js
- /src/renderers/dom/__tests__/ReactDOMProduction-test.js
- /src/renderers/dom/fiber/__tests__/ReactDOMFiber-test.js
- /src/renderers/dom/shared/__tests__/.*
- /src/renderers/dom/shared/eventPlugins/__tests__/.*
- /src/renderers/dom/shared/syntheticEvents/__tests__/.*
- /src/renderers/dom/shared/utils/.*
- /src/renderers/dom/shared/wrappers/__tests__/.*
- /src/renderers/native/__tests__/.*
- /src/renderers/shared/__tests__/ReactDebugTool-test.js
- /src/renderers/shared/fiber/__tests__/.*
- /src/renderers/shared/stack/reconciler/__tests__/Transaction-test.js
- /src/renderers/shared/utils/.*
- /src/renderers/testing/.*
- /src/test/.*
component_depth: 1
languages:
- cpp
- javascript
- python
- script
- typescript
